# Generated by Django 2.1.15 on 2021-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='Id_Categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(db_column='Id_Cliente', primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=500, null=True)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=8, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('primernombre', models.CharField(db_column='PrimerNombre', max_length=200)),
                ('segundonombre', models.CharField(blank=True, db_column='SegundoNombre', max_length=200, null=True)),
                ('primerapellido', models.CharField(db_column='PrimerApellido', max_length=200)),
                ('segundoapellido', models.CharField(blank=True, db_column='SegundoApellido', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id_detalle', models.IntegerField(db_column='Id_Detalle', primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=13)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=13)),
            ],
            options={
                'db_table': 'Detalles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_factura', models.IntegerField(db_column='Id_Factura', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'Facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(db_column='Id_Producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=250)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=13)),
                ('stock', models.IntegerField(db_column='Stock')),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
    ]
