# Generated by Django 2.1.15 on 2021-04-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargosEmpleados',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'cargos_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEncargo',
            fields=[
                ('id_encargo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_encargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=30)),
                ('nombre2', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encargos',
            fields=[
                ('id_encargos', models.IntegerField(primary_key=True, serialize=False)),
                ('anticipo', models.FloatField()),
                ('fecha_encargo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('detalle', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'encargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
                ('unidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduccionProductos',
            fields=[
                ('id_producto_produccion', models.ForeignKey(db_column='id_producto_produccion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestion.Productos')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'produccion_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=40)),
                ('nombre2', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedoresInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'proveedores_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestion.Productos')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('precio_unidad', models.FloatField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='facturas',
            table='facturas',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
